site_name: openIoTwx
theme:
  name: material
  custom_dir: material
  font:
    text: Roboto

nav:
  - Home:
    - Welcome: "index.md"
  - Guide Usage: "guide.md"
  - openIoTwx Introduction:
    - Platform: "introduction/platform.md"
    - Community: "introduction/community.md"
    - Ideals: "introduction/ideals.md"
  - Getting Started:
    - Materials list: "getting-started/materials.md"
    - Computing needs: "getting-started/computing.md"
    - Software tools: "getting-started/software.md"
  - Print: "print.md"
  - Install:
    - Flash: "installation/core_install.md"
    - Arduino Code: "installation/code.md"
  - Assemble:
    - Power and Internet: 'assemble/connection.md'
    - Testing: "assemble/testing.md"
    - Core Unit: "assemble/core.md"
    - Accessory Node Addition: "assemble/accessory_assemble.md"
  - Deploy: #Include calibration?
    - Core Unit: "deploying/core_deploy.md"
    - Accessory Nodes: "deploying/accessory_deploy.md"
  - Data Management: "data_management.md"
  - Contribution: "contribution.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
